[package]
name          = "grug-db-memory"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
grug-app   = { workspace = true }
grug-jmt   = { workspace = true }
grug-types = { workspace = true }
ics23      = { workspace = true }
thiserror  = { workspace = true }

[dev-dependencies]
