[workspace]
resolver = "2"
members = ["bin/*", "contracts/*", "crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
anyhow             = "1"
data-encoding      = "2"
digest             = "0.10"
hex                = "0.4"
k256               = "0.13"
p256               = "0.13"
proc-macro2        = "1"
quote              = "1"
rand               = "0.8"
serde              = "1"
serde_json         = "1"
serde-json-wasm    = "1"
sha2               = "0.10"
syn                = "1"
thiserror          = "1"
tracing            = "0.1"
tracing-subscriber = "0.3"
wasmer             = "4"

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
overflow-checks  = true
opt-level        = 3
panic            = "abort"
rpath            = false
