[workspace]
resolver = "2"
members  = [
  "dango/contracts/account/factory",
  "dango/contracts/account/safe",
  "dango/contracts/account/spot",
  "dango/contracts/amm",
  "dango/contracts/bank",
  "dango/contracts/ibc-transfer",
  "dango/contracts/taxman",
  "dango/contracts/token-factory",
  "dango/crates/auth",
  "dango/crates/dango",
  "dango/crates/genesis",
  "dango/crates/e2e",
  "grug/bin",
  "grug/contracts/mocks/account",
  "grug/contracts/mocks/bank",
  "grug/contracts/mocks/taxman",
  "grug/contracts/tester",
  "grug/crates/app",
  "grug/crates/client",
  "grug/crates/crypto",
  "grug/crates/db/disk",
  "grug/crates/db/memory",
  "grug/crates/ffi",
  "grug/crates/jellyfish-merkle",
  "grug/crates/macros",
  "grug/crates/math",
  "grug/crates/std",
  "grug/crates/storage",
  "grug/crates/testing",
  "grug/crates/types",
  "grug/crates/vm/rust",
  "grug/crates/vm/wasm",
]

[workspace.package]
version       = "0.0.0"
authors       = ["Left Curve Software Limited (https://leftcurve.software/)"]
edition       = "2021"
rust-version  = "1.80"
documentation = "https://leftcurve.software/grug"
repository    = "https://github.com/left-curve/grug"
license       = "TBD"
keywords      = ["blockchain", "wasm"]
categories    = ["cryptography::cryptocurrencies"]

[workspace.dependencies]
anyhow             = "1"
base64             = "0.22" # TODO: used in dango-auth; replace with data-encoding
blake2             = "0.10"
blake3             = "1"
bnum               = "0.12"
borsh              = "1"
chrono             = "0.4"
clap               = "4"
clru               = "0.6"
colored            = "2"
colored_json       = "5"
criterion          = "0.5"
data-encoding      = "2"
dialoguer          = "0.11"
digest             = "0.10"
dyn-clone          = "1"
ed25519-dalek      = "2"
elsa               = "1"
hex                = "0.4"
hex-literal        = "0.4"
home               = "0.5"
ics23              = "0.12"
k256               = "0.13"
paste              = "1"
p256               = "0.13"
proc-macro2        = "1"
proptest           = "1"
prost              = "0.13"
quote              = "1"
rand               = "0.8"
ripemd             = "0.1"
# Use the latest `master` branch of rust-rocksdb, which includes support for
# the user-defined timestamp feature:
# https://github.com/facebook/rocksdb/wiki/User-defined-Timestamp
#
# TODO: Update to v0.23.0 once released.
rocksdb            = { git = "https://github.com/rust-rocksdb/rust-rocksdb", rev = "1710120" }
serde              = "1"
serde_json         = "1"
serde_with         = "3"
sha2               = "0.10"
sha3               = "0.10"
signature          = "2"
syn                = "2"
tempfile           = "3"
tendermint         = "0.39"
tendermint-abci    = "0.39"
tendermint-proto   = "0.39"
tendermint-rpc     = "0.39"
test-case          = "3"
thiserror          = "1"
tokio              = "1"
tracing            = "0.1"
tracing-subscriber = "0.3"
wasmer             = "4"
wasmer-middlewares = "4"

# Grug packages
grug              = { path = "grug/crates/std" }
grug-app          = { path = "grug/crates/app" }
grug-auth         = { path = "grug/crates/auth" }
grug-client       = { path = "grug/crates/client" }
grug-crypto       = { path = "grug/crates/crypto" }
grug-db-disk      = { path = "grug/crates/db/disk" }
grug-db-memory    = { path = "grug/crates/db/memory" }
grug-ffi          = { path = "grug/crates/ffi" }
grug-jmt          = { path = "grug/crates/jellyfish-merkle" }
grug-macros       = { path = "grug/crates/macros" }
grug-math         = { path = "grug/crates/math" }
grug-mock-account = { path = "grug/contracts/mocks/account" }
grug-mock-bank    = { path = "grug/contracts/mocks/bank" }
grug-mock-taxman  = { path = "grug/contracts/mocks/taxman" }
grug-storage      = { path = "grug/crates/storage" }
grug-tester       = { path = "grug/contracts/tester" }
grug-testing      = { path = "grug/crates/testing" }
grug-types        = { path = "grug/crates/types" }
grug-vm-rust      = { path = "grug/crates/vm/rust" }
grug-vm-wasm      = { path = "grug/crates/vm/wasm" }

# Dango packages
dango-account-factory = { path = "dango/contracts/account/factory" }
dango-account-safe    = { path = "dango/contracts/account/safe" }
dango-account-spot    = { path = "dango/contracts/account/spot" }
dango-amm             = { path = "dango/contracts/amm" }
dango-auth            = { path = "dango/crates/auth" }
dango-bank            = { path = "dango/contracts/bank" }
dango-genesis         = { path = "dango/crates/genesis" }
dango-ibc-transfer    = { path = "dango/contracts/ibc-transfer" }
dango-taxman          = { path = "dango/contracts/taxman" }
dango-token-factory   = { path = "dango/contracts/token-factory" }
dango-types           = { path = "dango/crates/dango" }

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
overflow-checks  = true
opt-level        = 3
panic            = "abort"
rpath            = false
