[workspace]
resolver = "2"
members = ["contracts/*", "crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
anyhow    = "1"
# Our fork of wasmi is based off its v0.32.0-beta.2 release, with the following
# changes:
# - Make Caller::new function public. We need this to contruct vm::Host object
wasmi     = { git = "https://github.com/cwsoftware123/wasmi", rev = "5f1d021" }
thiserror = "1"

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
overflow-checks  = true
opt-level        = 3
panic            = "abort"
rpath            = false
