[workspace]
resolver = "2"
members = ["guests/*", "host", "sdk"]

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
anyhow    = "1"
wasmi     = { git = "https://github.com/larry0x/wasmi", rev = "950d877" }
thiserror = "1"

[workspace.lints.clippy]
missing_safety_doc = "allow"

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
overflow-checks  = true
opt-level        = 3
panic            = "abort"
rpath            = false
