[workspace]
resolver = "2"
members  = [
  "bin/*",
  "contracts/account",
  "contracts/bank",
  "contracts/mocks/*",
  "crates/*",
  "sdk/rust",
]

[workspace.package]
version       = "0.0.0"
authors       = ["Larry Lyu <gm@larry.engineer>"]
edition       = "2021"
rust-version  = "1.73"
documentation = "https://larry.engineer/cwd" # TODO: update this once we have a docs site
repository    = "https://github.com/cwsoftware123/cwd"
license       = "TBD"
keywords      = ["blockchain", "wasm"]
categories    = ["cryptography::cryptocurrencies"]

[workspace.dependencies]
aes-gcm            = "0.10"
anyhow             = "1"
bip32              = "0.5"
cfg-if             = "1"
clap               = "4"
colored            = "2"
colored_json       = "4"
data-encoding      = "2"
dialoguer          = "0.11"
digest             = "0.10"
dyn-clone          = "1"
forward_ref        = "1"
hex                = "0.4"
hex-literal        = "0.4"
home               = "0.5"
k256               = "0.13"
lazy_static        = "1"
p256               = "0.13"
password-hash      = "0.5"
pbkdf2             = "0.12"
proc-macro2        = "1"
quote              = "1"
rand               = "0.8"
serde              = "1"
serde_json         = "1"
serde-json-wasm    = "1"
serde_with         = "3"
sha2               = "0.10"
signature          = "2"
syn                = "1"
tendermint         = "0.34"
tendermint-abci    = "0.34"
tendermint-proto   = "0.34"
tendermint-rpc     = "0.34"
thiserror          = "1"
tokio              = "1"
tracing            = "0.1"
tracing-subscriber = "0.3"
wasmer             = "4"

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
overflow-checks  = true
opt-level        = 3
panic            = "abort"
rpath            = false
