[workspace]
resolver = "2"
members = ["contracts/*", "crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
anyhow          = "1"
hex             = "0.4"
lazy_static     = "1"
schemars        = "0.8"
serde           = "1"
serde-json-wasm = "1"
# Our fork of wasmi is based off its v0.32.0-beta.2 release, with the following
# changes:
# - Make Caller::new function public. We need this to contruct vm::Host object.
# - Add an `anyhow` feature, which allows host functions to emit anyhow::Error.
wasmi = { git = "https://github.com/cwsoftware123/wasmi", rev = "e122dfa", features = ["anyhow"] }

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
overflow-checks  = true
opt-level        = 3
panic            = "abort"
rpath            = false
