[workspace]
resolver = "2"
members = ["bin/*", "contracts/*", "crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
anyhow             = "1"
blake3             = "1"
data-encoding      = "2"
digest             = "0.10"
hex                = "0.4"
k256               = "0.13"
p256               = "0.13"
proc-macro2        = "1"
quote              = "1"
rand               = "0.8"
serde              = "1"
serde_json         = "1"
serde-json-wasm    = "1"
syn                = "1"
tracing            = "0.1"
tracing-subscriber = "0.3"

# Our fork of wasmi is based off its v0.32.0-beta.2 release, with the following
# changes:
# - Make Caller::new function public. We need this to contruct vm::Host object.
# - Add an `anyhow` feature, which allows host functions to emit anyhow::Error.
wasmi = { git = "https://github.com/cwsoftware123/wasmi", rev = "e122dfa", features = ["anyhow"] }

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
overflow-checks  = true
opt-level        = 3
panic            = "abort"
rpath            = false
