# https://rust-lang.github.io/rustfmt/
comment_width                = 80     # unstable
condense_wildcard_suffixes   = true   # unstable
doc_comment_code_block_width = 80     # unstable
enum_discrim_align_threshold = 100    # unstable
format_code_in_doc_comments  = true   # unstable
format_macro_matchers        = true   # unstable
group_imports                = "One"  # unstable
imports_granularity          = "One"  # unstable
match_block_trailing_comma   = true
max_width                    = 100
normalize_comments           = true   # unstable
normalize_doc_attributes     = true   # unstable
overflow_delimited_expr      = true   # unstable
reorder_impl_items           = true   # unstable
struct_field_align_threshold = 100    # unstable
struct_lit_single_line       = false  # unstable
struct_lit_width             = 0
struct_variant_width         = 0
use_field_init_shorthand     = true
use_small_heuristics         = "Off"
use_try_shorthand            = true
wrap_comments                = true   # unstable
