[package]
name          = "cw-vm-rust"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
borsh     = { workspace = true, features = ["derive", "de_strict_order"] }
cw-app    = { path = "../../app" }
cw-crypto = { path = "../../crypto" }
cw-types  = { path = "../../types" }
cw-wasm   = { path = "../../wasm" }
elsa      = { workspace = true }
serde     = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
