[package]
name          = "cw-app"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
cw-db            = { path = "../db" }
cw-jmt           = { path = "../jellyfish-merkle" }
cw-std           = { path = "../std" }
cw-vm            = { path = "../vm" }
dyn-clone        = { workspace = true }
hex              = { workspace = true }
prost            = { workspace = true }
tendermint-proto = { workspace = true }
tendermint-abci  = { workspace = true }
thiserror        = { workspace = true }
tracing          = { workspace = true }

[dev-dependencies]
anyhow             = { workspace = true }
cfg-if             = { workspace = true }
cw-account         = { path = "../../contracts/account", features = ["library"] }
cw-bank            = { path = "../../contracts/bank", features = ["library"] }
cw-crypto          = { path = "../../crates/crypto" }
cw-mock-querier    = { path = "../../contracts/mocks/querier" }
k256               = { workspace = true }
lazy_static        = { workspace = true }
rand               = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
tracing-subscriber = { workspace = true }
