[package]
name          = "cw-app"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
cw-std           = { path = "../std" }
dyn-clone        = { workspace = true }
hex              = { workspace = true }
prost            = { workspace = true }
tendermint-proto = { workspace = true }
tendermint-abci  = { workspace = true }
thiserror        = { workspace = true }
tracing          = { workspace = true }

[dev-dependencies]
