[package]
name    = "cw-app"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
cw-db            = { path = "../db" }
cw-std           = { path = "../std" }
cw-vm            = { path = "../vm" }
hex              = { workspace = true }
tendermint-proto = { workspace = true }
tendermint-abci  = { workspace = true }
thiserror        = { workspace = true }
tracing          = { workspace = true }

[dev-dependencies]
anyhow             = { workspace = true }
cfg-if             = { workspace = true }
cw-account         = { path = "../../contracts/account" }
cw-bank            = { path = "../../contracts/bank" }
cw-crypto          = { path = "../../crates/crypto" }
cw-mock-querier    = { path = "../../contracts/mocks/querier" }
k256               = { workspace = true }
lazy_static        = { workspace = true }
rand               = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
tracing-subscriber = { workspace = true }
