[package]
name    = "cw-app"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow          = { workspace = true }
cw-db           = { path = "../db" }
cw-std          = { path = "../std" }
cw-vm           = { path = "../vm" }
serde-json-wasm = { workspace = true }
tracing         = { workspace = true }
wasmi           = { workspace = true }

[dev-dependencies]
cw-account         = { path = "../../contracts/account" }
cw-bank            = { path = "../../contracts/bank" }
cw-crypto          = { path = "../../crates/crypto" }
k256               = { workspace = true }
rand               = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
tracing-subscriber = { workspace = true }
