[package]
name    = "cw-app"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow          = { workspace = true }
cw-std          = { path = "../std", features = ["storage-utils"] }
cw-vm           = { path = "../vm" }
serde-json-wasm = { workspace = true }
tracing         = { workspace = true }
wasmi           = { workspace = true }

[dev-dependencies]
cw-bank            = { path = "../../contracts/bank" }
serde              = { workspace = true }
serde_json         = { workspace = true }
tracing-subscriber = { workspace = true }
