[package]
name    = "cw-bank"
version = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = { workspace = true }
cw-sdk = { path = "../../crates/sdk" }
