[package]
name    = "cw-account"
version = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = { workspace = true }
cw-std = { path = "../../crates/std" }
sha2   = { workspace = true }
