[package]
name    = "cwcli"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow             = { workspace = true }
clap               = { workspace = true, features = ["derive", "wrap_help"] }
cw-std             = { path = "../../crates/std" }
hex                = { workspace = true }
tendermint-rpc     = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
