[package]
name          = "cwcli"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
anyhow         = { workspace = true }
bip32          = { workspace = true }
clap           = { workspace = true, features = ["derive", "wrap_help"] }
colored        = { workspace = true }
colored_json   = { workspace = true }
cw-merkle      = { path = "../../crates/merkle" }
cw-rs          = { path = "../../sdk/rust" }
cw-std         = { path = "../../crates/std" }
dialoguer      = { workspace = true }
hex            = { workspace = true }
home           = { workspace = true }
rand           = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
tendermint-rpc = { workspace = true, features = ["http-client"] }
tokio          = { workspace = true }
