[package]
name          = "cwcli"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
anyhow         = { workspace = true }
clap           = { workspace = true, features = ["derive", "wrap_help"] }
cw-account     = { path = "../../contracts/account" }
cw-keyring     = { path = "../../crates/keyring" }
cw-std         = { path = "../../crates/std" }
hex            = { workspace = true }
home           = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
tendermint-rpc = { workspace = true, features = ["http-client"] }
tokio          = { workspace = true }
