[package]
name    = "cwcli"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow         = { workspace = true }
clap           = { workspace = true, features = ["derive", "wrap_help"] }
cw-std         = { path = "../../crates/std" }
hex            = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
tendermint-rpc = { workspace = true, features = ["http-client"] }
tokio          = { workspace = true }
