[package]
name          = "bob"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
serde = { workspace = true, features = ["derive"] }
toml  = { workspace = true }

[dev-dependencies]
