[package]
name    = "cw-db"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cw-std = { path = "../std", features = ["storage-utils"] }
cw-vm  = { path = "../vm" }
