[package]
name          = "cwd"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
anyhow             = { workspace = true }
clap               = { workspace = true, features = ["derive", "wrap_help"] }
cw-app             = { path = "../../crates/app" }
cw-db-disk         = { path = "../../crates/db/disk" }
cw-vm-wasm         = { path = "../../crates/vm/wasm" }
home               = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
