[package]
name    = "cwd"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow             = { workspace = true }
clap               = { workspace = true, features = ["derive", "wrap_help"] }
cw-app             = { path = "../../crates/app" }
cw-db              = { path = "../../crates/db" }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
