[package]
name    = "cw-vm"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow             = { workspace = true }
cw-std             = { path = "../std" }
data-encoding      = { workspace = true }
serde              = { workspace = true }
serde-json-wasm    = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
wasmi              = { workspace = true }

[dev-dependencies]
cw-bank = { path = "../../contracts/bank" }
