[package]
name    = "cw-vm"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow        = { workspace = true }
cw-crypto     = { path = "../crypto" }
cw-std        = { path = "../std" }
data-encoding = { workspace = true }
serde         = { workspace = true }
tracing       = { workspace = true }
wasmi         = { workspace = true }

[dev-dependencies]
cw-bank            = { path = "../../contracts/bank" }
serde_json         = { workspace = true }
tracing-subscriber = { workspace = true }
