[package]
name          = "cw-std"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
cw-std-derive   = { path = "./derive" }
data-encoding   = { workspace = true }
hex             = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
serde-json-wasm = { workspace = true }
sha2            = { workspace = true }
thiserror       = { workspace = true }
