[package]
name          = "cw-std"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
borsh      = { workspace = true, features = ["derive", "de_strict_order"] }
cw-macros  = { path = "../macros" }
cw-storage = { path = "../storage" }
cw-testing = { path = "../testing" }
cw-types   = { path = "../types" }
cw-wasm    = { path = "../wasm" }
serde      = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }

[dev-dependencies]
