[package]
name          = "cw-wasm"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
borsh    = { workspace = true, features = ["derive", "de_strict_order"] }
cw-types = { path = "../types" }
serde    = { workspace = true }

[dev-dependencies]
