[package]
name          = "cw-rs"
description   = "The Rust SDK for Cosmos Wasm Daemon"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
aes-gcm            = { workspace = true, features = ["std"] }
anyhow             = { workspace = true }
bip32              = { workspace = true }
cw-account         = { path = "../../contracts/account", features = ["library"] }
cw-account-factory = { path = "../../contracts/account-factory", features = ["library"] }
cw-crypto          = { path = "../../crates/crypto" }
cw-merkle          = { path = "../../crates/merkle" }
cw-std             = { path = "../../crates/std" }
hex                = { workspace = true }
home               = { workspace = true }
k256               = { workspace = true }
lazy_static        = { workspace = true }
pbkdf2             = { workspace = true }
rand               = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
sha2               = { workspace = true }
signature          = { workspace = true }
tendermint         = { workspace = true }
tendermint-rpc     = { workspace = true, features = ["http-client"] }

[dev-dependencies]
cw-bank               = { path = "../../contracts/bank", features = ["library"] }
cw-ibc-solomachine    = { path = "../../contracts/ibc/clients/solomachine", features = ["library"] }
cw-mock-token-wrapper = { path = "../../contracts/mocks/token-wrapper", features = ["library"] }
hex-literal           = { workspace = true }
tokio                 = { workspace = true }
