[package]
name          = "cw-testing"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
cw-app       = { path = "../app" }
cw-db-memory = { path = "../db/memory" }
cw-types     = { path = "../types" }
cw-vm-rust   = { path = "../vm/rust" }

[dev-dependencies]
cw-wasm = { path = "../wasm" }
