[package]
name          = "cw-db-memory"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
cw-app    = { path = "../../app" }
cw-jmt    = { path = "../../jellyfish-merkle" }
cw-types  = { path = "../../types" }
thiserror = { workspace = true }

[dev-dependencies]
