[package]
name    = "cw-state-machine"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
cw-db  = { path = "../db" }
cw-std = { path = "../std" }
cw-vm  = { path = "../vm" }
