[package]
name          = "cw-jellyfish-merkle"
description   = "A minimalist implementation of Jellyfish Merkle tree (JMT)"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[features]
default = ["debug"]
# MerkleTree exposes `nodes` and `orphans` function for enumerating these records
# in storage. Useful for debugging.
debug = []

[dependencies]
cw-std = { path = "../std" }
sha2   = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
