[package]
name          = "cw-crypto"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
anyhow = { workspace = true }
digest = { workspace = true }
k256   = { workspace = true }
p256   = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
sha2 = { workspace = true }
