[package]
name    = "cw-crypto"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
blake3 = { workspace = true }
digest = { workspace = true }
k256   = { workspace = true }
p256   = { workspace = true }

[dev-dependencies]
rand = "0.8"
