name: JavaScript

on: push

jobs:
  js-tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
          node-version: "lts/*"

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test

  js-lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
          node-version: "lts/*"

      - name: Install dependencies
        run: yarn install

      - name: Lints
        run: yarn ci
