name: JavaScript SDK

on: push

jobs:
  js-sdk-checks:
    name: JavaScript SDK Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          cache-dependency-path: "sdk/js/yarn.lock"
          node-version: "lts/*"

      - name: Install dependencies
        working-directory: sdk/js
        run: yarn install

      - name: Typecheck
        working-directory: sdk/js
        run: yarn check:type

      - name: Build
        working-directory: sdk/js
        run: yarn build

      - name: Test
        working-directory: sdk/js
        run: yarn test
