name: Landing Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "develop"
    paths:
      - "grug/sdk/packages/react/**"
      - "dango/ui/shared/**"
      - "dango/ui/landing/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "grug/sdk/packages/react/**"
      - "dango/ui/shared/**"
      - "dango/ui/landing/**"

jobs:
  deploy:
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: "sdk"
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install SDK dependencies
        working-directory: "grug/sdk"
        run: pnpm i --frozen-lockfile

      - name: Build SDK
        run: pnpm build:pkg

      - name: Install Dango dependencies
        working-directory: "dango/ui"
        run: pnpm i --frozen-lockfile

      - name: Build Landing
        run: pnpm build:landing

      - name: Uploading to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          wranglerVersion: "3"
          apiToken: ${{ secrets.CF_TOKEN }}
          accountId: 9f30716e11f27c296dfbadb7b7571ae6
          projectName: dango-portal
          directory: ./dango/ui/landing/.vercel/output/static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${GITHUB_REF##*/}
