name: PR Packages Checks

on:
  pull_request:
    paths:
      - "grug/sdk/packages/**"

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "grug/sdk"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install SDK dependencies
        run: pnpm i --frozen-lockfile

      - name: Linter checks
        run: pnpm lint:pkg

      - name: Build checks
        run: pnpm build:pkg

      - name: Doc Build Check
        run: pnpm doc
