name: Rust

on: push

jobs:
  examples:
    name: Examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Build Wasm binary
        run: cargo build --target wasm32-unknown-unknown -p add -p bank -p greeter
        env:
          RUST_BACKTRACE: 1

      - name: Run add example
        run: cargo run -p host --example add
        env:
          RUST_BACKTRACE: 1

      - name: Run greeter example
        run: cargo run -p host --example greeter
        env:
          RUST_BACKTRACE: 1

      - name: Run bank example
        run: cargo run -p host --example bank
        env:
          RUST_BACKTRACE: 1

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy

      - name: Run clippy
        run: cargo clippy --tests -- -D warnings
